using System;
using System.Collections.Generic;
using System.Text;
using MathWorks.MATLAB.NET.Arrays;
using MathWorks.MATLAB.NET.Utility;
using EstimateTimeFun;

/// <summary>
/// Sample driver code that integrates a compiled MATLAB function
/// generated by MATLAB Compiler SDK
///
/// Refer to the MATLAB Compiler SDK documentation for more
/// information.
/// </summary>
class EstimateTimeFunSample1 {

	static EClass eclassInstance;

	static void Setup() {
		eclassInstance = new EClass();
	}

	/// <summary>
	/// Example of using the EstimateTimeFun function.
	/// </summary>
	public static void EstimateTimeFunSample() {
		MWNumericArray timeOut = null;
		Object[] results = null;
		try {
			results = eclassInstance.EstimateTimeFun(1);
			if (results[0] is MWNumericArray) {
				timeOut = (MWNumericArray) results[0];
			}
			Console.WriteLine(timeOut);
		} catch (Exception e) {
			Console.WriteLine(e);
		}
	}

	/// <summary>
	/// The main entry point for the application.
	/// </summary>
	static void Main(string[] args) {
		try {
			Setup();
		} catch (Exception e) {
			Console.WriteLine(e);
			Environment.Exit(1);
		}
		try {
			EstimateTimeFunSample();
		} catch (Exception e) {
			Console.WriteLine(e);
			Environment.Exit(1);
		}
	}

}
